root: true
env:
  browser: true
  es6: true
  node: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules: {}
settings:
  react:
    version: "16.12.0"
ignorePatterns: [ 'serviceWorker.js' ]
